pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/playwright/python:v1.40.0-jammy'
        }
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Build') {
            steps {
                sh 'pytest lesson_26/tests/test_login.py'
            }
        }
        stage('Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: 'allure-reports',
                    results: [[path: 'test_results']]
                ])
            }
        }
    }
    post {
        always {
            emailext body: "Build URL: ${BUILD_URL}",
                     subject: "Jenkins Build ${BUILD_NUMBER}: " + currentBuild.currentResult,
                     to: 'carl4welps@gmail.com'
        }
    }
}