pipeline {
    agent any
    stages {
        stage('Install dependencies'){
            steps{
                sh 'python3 -m venv venv'
                sh 'venv/bin/pip install -r requirements.txt'
            }
        }
        stage('Build'){
            steps{
                sh 'venv/bin/playwright install'
                sh 'xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" venv/bin/pytest lesson_26/tests/test_login.py'            }
        }
        stage('Report'){
            steps{
                allure([
                    includeProperties: false,
                    jdk: 'allure-reports',
                    results: [[path: 'test_results']]
                ])
            }
        }
    }
//        post{
//        always {
//            emailext body: "Build URL: ${BUILD_URL}",
//                     subject: "Jenkins Build ${BUILD_NUMBER}: " + currentBuild.currentResult,
//                     to: 'carl4welps@gmail.com'
//        }

    }